spring.application.name=BackendApi
spring.datasource.url=jdbc:h2:mem:coindeskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=zxc
spring.jpa.hibernate.ddl-auto=update
